# 1. 1NN for Iris Dataset and Test Error Rate

In [566]:
import numpy as np

In [567]:
#Function to find the euclidean distance
def predi(test_sample,x_train):
    n_distances = []
    for train_sample in x_train:
        distance = 0
        for i in range(len(test_sample)):
            distance += (train_sample[i] - test_sample[i])**2
        n_distances.append(np.sqrt(distance))
    return n_distances

In [568]:
#Function to find the minimum
def minimum(n_distances):
    min_val = n_distances[0]
    min_ind = 0
    for i in range(len(n_distances)):
        if n_distances[i] < min_val:
            min_val = n_distances[i]
            min_ind = i
    return min_ind

In [569]:
# Main function to find the 1 nearest neighbor
def nn(x_train,x_test,y_train,y_test):
    import numpy as np
    y_pred = []
    for test_sample in x_test:
        dist = predi(test_sample,x_train)
        min_index = minimum(dist)
        y_pred.append(y_train[min_index])
    error_rate = np.mean(y_pred != y_test)
    print("The test error rate for the dataset is :",error_rate)

In [570]:
from sklearn.datasets import load_iris
iris = load_iris()

In [571]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train ,y_test = train_test_split(iris['data'],iris['target'],random_state=236)

In [572]:
print(X_train.shape)
print(X_train)

(112, 4)
[[5.6 2.8 4.9 2. ]
 [6.5 3.  5.8 2.2]
 [5.8 2.7 5.1 1.9]
 [6.1 2.9 4.7 1.4]
 [5.9 3.2 4.8 1.8]
 [6.3 2.5 4.9 1.5]
 [5.1 3.5 1.4 0.2]
 [5.4 3.9 1.3 0.4]
 [5.6 2.7 4.2 1.3]
 [5.5 2.6 4.4 1.2]
 [6.7 3.3 5.7 2.5]
 [5.8 2.7 4.1 1. ]
 [5.6 2.5 3.9 1.1]
 [6.9 3.1 5.1 2.3]
 [6.3 2.5 5.  1.9]
 [5.  3.5 1.3 0.3]
 [6.7 3.1 4.4 1.4]
 [5.  3.4 1.6 0.4]
 [6.5 3.2 5.1 2. ]
 [5.  3.6 1.4 0.2]
 [5.7 3.  4.2 1.2]
 [6.3 3.3 6.  2.5]
 [6.5 2.8 4.6 1.5]
 [5.5 2.4 3.7 1. ]
 [7.9 3.8 6.4 2. ]
 [5.8 2.6 4.  1.2]
 [6.7 3.  5.  1.7]
 [5.4 3.  4.5 1.5]
 [5.1 3.4 1.5 0.2]
 [6.  2.7 5.1 1.6]
 [6.9 3.2 5.7 2.3]
 [7.7 3.8 6.7 2.2]
 [5.4 3.7 1.5 0.2]
 [5.4 3.9 1.7 0.4]
 [6.6 3.  4.4 1.4]
 [5.  3.4 1.5 0.2]
 [6.3 2.9 5.6 1.8]
 [5.2 3.5 1.5 0.2]
 [5.6 3.  4.1 1.3]
 [5.1 3.8 1.9 0.4]
 [6.3 2.7 4.9 1.8]
 [5.  3.5 1.6 0.6]
 [5.9 3.  4.2 1.5]
 [4.8 3.  1.4 0.3]
 [5.6 3.  4.5 1.5]
 [5.1 3.3 1.7 0.5]
 [4.6 3.1 1.5 0.2]
 [6.2 2.2 4.5 1.5]
 [5.  3.2 1.2 0.2]
 [5.  3.3 1.4 0.2]
 [5.  2.3 3.3 1. ]
 [4.9 3.6 1.4 0.1]
 [6

In [573]:
print(X_test.shape)
print(X_test)

(38, 4)
[[6.9 3.1 5.4 2.1]
 [6.  2.2 4.  1. ]
 [7.4 2.8 6.1 1.9]
 [5.5 2.5 4.  1.3]
 [4.6 3.2 1.4 0.2]
 [5.7 2.9 4.2 1.3]
 [6.3 3.4 5.6 2.4]
 [5.7 3.8 1.7 0.3]
 [6.7 3.3 5.7 2.1]
 [5.7 4.4 1.5 0.4]
 [6.1 3.  4.9 1.8]
 [5.8 4.  1.2 0.2]
 [5.1 3.8 1.6 0.2]
 [6.1 3.  4.6 1.4]
 [6.3 2.8 5.1 1.5]
 [6.2 2.8 4.8 1.8]
 [5.4 3.4 1.7 0.2]
 [6.1 2.8 4.7 1.2]
 [5.8 2.7 5.1 1.9]
 [6.4 3.2 4.5 1.5]
 [5.6 2.9 3.6 1.3]
 [5.1 2.5 3.  1.1]
 [5.5 2.3 4.  1.3]
 [7.2 3.2 6.  1.8]
 [6.7 3.1 5.6 2.4]
 [5.7 2.8 4.5 1.3]
 [5.5 3.5 1.3 0.2]
 [6.4 3.1 5.5 1.8]
 [7.7 2.8 6.7 2. ]
 [5.5 4.2 1.4 0.2]
 [4.8 3.1 1.6 0.2]
 [5.1 3.7 1.5 0.4]
 [7.1 3.  5.9 2.1]
 [4.6 3.4 1.4 0.3]
 [6.8 2.8 4.8 1.4]
 [6.3 2.3 4.4 1.3]
 [5.4 3.4 1.5 0.4]
 [6.4 2.7 5.3 1.9]]


In [574]:
nn(X_train , X_test , y_train ,y_test)

The test error rate for the dataset is : 0.02631578947368421


# 2. 1NN for Ionosphere Dataset and Test Error Rate

In [575]:
import numpy as np
Xj = np.genfromtxt("ionosphere.txt",delimiter = ",",usecols = np.arange(34))

In [576]:
Xj[:3]

array([[ 1.     ,  0.     ,  0.99539, -0.05889,  0.85243,  0.02306,
         0.83398, -0.37708,  1.     ,  0.0376 ,  0.85243, -0.17755,
         0.59755, -0.44945,  0.60536, -0.38223,  0.84356, -0.38542,
         0.58212, -0.32192,  0.56971, -0.29674,  0.36946, -0.47357,
         0.56811, -0.51171,  0.41078, -0.46168,  0.21266, -0.3409 ,
         0.42267, -0.54487,  0.18641, -0.453  ],
       [ 1.     ,  0.     ,  1.     , -0.18829,  0.93035, -0.36156,
        -0.10868, -0.93597,  1.     , -0.04549,  0.50874, -0.67743,
         0.34432, -0.69707, -0.51685, -0.97515,  0.05499, -0.62237,
         0.33109, -1.     , -0.13151, -0.453  , -0.18056, -0.35734,
        -0.20332, -0.26569, -0.20468, -0.18401, -0.1904 , -0.11593,
        -0.16626, -0.06288, -0.13738, -0.02447],
       [ 1.     ,  0.     ,  1.     , -0.03365,  1.     ,  0.00485,
         1.     , -0.12062,  0.88965,  0.01198,  0.73082,  0.05346,
         0.85443,  0.00827,  0.54591,  0.00299,  0.83775, -0.13644,
         0.75535, 

In [577]:
yj = np.genfromtxt("ionosphere.txt",delimiter = ",", usecols = 34 , dtype = 'int')


In [578]:
yj[:]

array([ 1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,
       -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,
        1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,
       -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,
        1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,
       -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,  1, -1,  1, -1,  1,
       -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,
        1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,
       -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,
        1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,
       -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,
        1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,
       -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,
        1, -1,  1, -1,  1

In [579]:
from sklearn.model_selection import train_test_split
xj_train,xj_test,Yj_train,Yj_test = train_test_split(Xj,yj,random_state = 236)

In [580]:
nn(xj_train,xj_test,Yj_train,Yj_test)

The test error rate for the dataset is : 0.1590909090909091


# 3. 3NN for Iris Dataset and Test Error Rate

In [581]:
import numpy as np
from scipy.stats import mode

In [582]:
def euclidean(row1,row2):
    distancess = 0
    for i in range(len(row1)):
        distancess += (row1[i]-row2[i])**2
    return(np.sqrt(distancess))

In [583]:
def predict_classify(x_train,y_train,x_input,n_neighbors=3):
    labels = []
    for i in x_input:
        nn_distance = []
        for j in range(len(x_train)):
            dis = euclidean(np.array(x_train[j,:]),i)
            nn_distance.append(dis)
        distancess = np.argsort(nn_distance)[:3]
        labelss = y_train[distancess]
        label = mode(labelss)
        label = label.mode[0]
        labels.append(label)
    return labels

In [584]:
from sklearn.datasets import load_iris
iris = load_iris()

In [585]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train ,y_test = train_test_split(iris['data'],iris['target'],random_state=236)

In [586]:
y_pred = predict_classify(X_train,y_train,X_test)

In [587]:
error_rate = np.mean(y_pred!=y_test)
print("The test error rate is :",error_rate)

The test error rate is : 0.02631578947368421


# 4. 3NN for Ionosphere Dataset and Test Error Rate

In [588]:
import numpy as np
XK = np.genfromtxt("ionosphere.txt",delimiter = ",",usecols = np.arange(34))

In [589]:
yK = np.genfromtxt("ionosphere.txt",delimiter = ",", usecols = 34 , dtype = 'int')

In [590]:
from sklearn.model_selection import train_test_split
xk_train,xk_test,Yk_train,Yk_test = train_test_split(XK,yK,random_state = 236)

In [591]:
y_predicted = predict_classify(xk_train,Yk_train,xk_test)

In [592]:
error_rate = np.mean(y_predicted != Yk_test)
print("The test error rate is :",error_rate)

The test error rate is : 0.125


# 5. Interesting observations of the Iris Dataset

Using Pandas gives a better understanding of the dataset and how it is constructed.

In [593]:
import pandas as pd
import matplotlib.pyplot as plt

In [594]:
#Reading the CSV file
iris = pd.read_csv("iris_csv.csv")

In [595]:
iris.head() #Printing the top 5 rows

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [596]:
iris.shape #There are 150 features and 5 columns in the dataset

(150, 5)

In [597]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   sepallength  150 non-null    float64
 1   sepalwidth   150 non-null    float64
 2   petallength  150 non-null    float64
 3   petalwidth   150 non-null    float64
 4   class        150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


Only 1 column has categorical data and all other columns are of non numerics types

In [598]:
iris.describe()

sepallength  sepalwidth  petallength  petalwidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.054000     3.758667    1.198667
std       0.828066    0.433594     1.764420    0.763161
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000

This gives us the count of each column along with their mean , standard deviation , minimum and maximum value

In [599]:
iris.isnull().sum()

sepallength    0
sepalwidth     0
petallength    0
petalwidth     0
class          0
dtype: int64

isnull() is used to check if there are any missing values.

# 6. Implementation of KNN for a general value of K

In [600]:
import numpy as np
from scipy.stats import mode

In [601]:
def euclidean_dist(row1,row2):
    distancess = 0
    for i in range(len(row1)):
        distancess += (row1[i]-row2[i])**2
    return(np.sqrt(distancess))

In [602]:
def predict_classi(x_train,y_train,x_input,n_neighbors):
    labels = []
    for i in x_input:
        nn_distance = []
        for j in range(len(x_train)):
            dis = euclidean(np.array(x_train[j,:]),i)
            nn_distance.append(dis)
        distancess = np.argsort(nn_distance)[:n_neighbors]
        labelss = y_train[distancess]
        label = mode(labelss)
        label = label.mode[0]
        labels.append(label)
    return labels

In [603]:
from sklearn.datasets import load_iris
iris = load_iris()

In [604]:
from sklearn.model_selection import train_test_split
xc_train,xc_test,yc_train,yc_test = train_test_split(iris['data'],iris['target'],random_state = 236)

In [605]:
y_predic = predict_classi(xc_train,yc_train,xc_test,9)

In [606]:
error_rate = np.mean(y_predic != yc_test)
print("The Test Error rate is :",error_rate)

The Test Error rate is : 0.07894736842105263


The above test error rate is for k = 9

In [607]:
y_predic = predict_classi(xc_train,yc_train,xc_test,11)
error_rate1 = np.mean(y_predic != yc_test)
print("The test error rate is :",error_rate1)

The test error rate is : 0.02631578947368421


The above Test error rate is for k = 11

# 7. Generalized KNN for Ionosphere Dataset.

In [608]:
import numpy as np
XC = np.genfromtxt("ionosphere.txt",delimiter = ",",usecols = np.arange(34))

In [609]:
yC = np.genfromtxt("ionosphere.txt",delimiter = ",", usecols = 34 , dtype = 'int')

In [610]:
from sklearn.model_selection import train_test_split
xC_train,xC_test,YC_train,YC_test = train_test_split(XC,yC,random_state = 236)

In [611]:
y_pre = predict_classi(xC_train,YC_train,xC_test,11)

In [612]:
error_rate = np.mean(y_pre != YC_test)
print("The test error rate is :",error_rate)

The test error rate is : 0.13636363636363635


The Test Error Rate shown above is for k = 11 for the ionosphere Dataset. Similarly the test error for any value of k can be depicted.

In [613]:
y_pre = predict_classi(xC_train,YC_train,xC_test,9)
error_rate = np.mean(y_pre != YC_test)
print("The test error rate is :",error_rate)

The test error rate is : 0.14772727272727273


The above test error rate displayed is for k = 9.

# KNN for Generalized value of K has been implemented and tested for both the Datasets as shown above. Also, the error rate is displayed for different values of K.